portal/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, Email, EqualTo, URL, ValidationError
from wtforms.fields.html5 import EmailField
from portal.models import Subscribers

class SubscribersForm(FlaskForm):
    email = EmailField(validators=[DataRequired(), Email()], render_kw={"placeholder": "Alamat Anda Email"})
    submit = SubmitField('Berlangganan')

    def validate_email(self, email):
        subscriber = Subscribers.query.filter_by(email=email.data).first()
        if subscriber:
            raise ValidationError('Email sudah pernah didaftarkan, cek email Anda')

class CommentForm(FlaskForm):
    nama = StringField('Nama',
                           validators=[DataRequired(), Length(min=3)], render_kw={'placeholder': 'Nama'})
    email = StringField('Email',
                        validators=[DataRequired(), Email()], render_kw={'placeholder': 'Email'})
    website = StringField('Website', render_kw={'placeholder': 'http://www.example.com'})
    comment = TextAreaField('Komentar', validators=[DataRequired()], render_kw={'placeholder': 'Tinggalkan komentar'})
    submit = SubmitField('Submit')

class ReplyForm(FlaskForm):
    nama = StringField('Nama',
                           validators=[DataRequired(), Length(min=3)], render_kw={'placeholder': 'Nama'})
    email = StringField('Email',
                        validators=[DataRequired(), Email()], render_kw={'placeholder': 'Email'})
    website = StringField('Website', render_kw={'placeholder': 'http://www.example.com'})
    comment = TextAreaField('Komentar', validators=[DataRequired()], render_kw={'placeholder': 'Tinggalkan komentar'})
    submit = SubmitField('Submit')

class HubungiForm(FlaskForm):
    nama = StringField('Nama',
                           validators=[DataRequired(), Length(min=3)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    pesan = TextAreaField('Pesan', validators=[DataRequired()])
    submit = SubmitField('Submit')

portal/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, current_app
from portal import db
from flask_login import current_user
from portal.posts.forms import HubungiForm, SubscribersForm, CommentForm
from portal.models import User, Role, Post, Comments, Kategori, Tag, Page, Hubungi, Subscribers
from .utils import utils_context
import datetime

posts = Blueprint('posts', __name__)


@posts.app_errorhandler(404)
def page_not_found(e):
    # note that we set the 404 status explicitly
    return render_template('error/404.html', **utils_context()), 404

@posts.app_errorhandler(403)
def page_deny(e):
    # note that we set the 404 status explicitly
    return render_template('error/403.html', **utils_context()), 403

@posts.before_app_first_request
def before_first_request_func():
    db.create_all()
    Role.insert_roles()

@posts.context_processor
def waktu():
    return utils_context()

@posts.route("/")
@posts.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    headline = Post.query.filter_by(headline = True).order_by(Post.date_posted.desc()).first()
    posts = Post.query.filter_by(publish=True).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('post/home.html', posts=posts, headline=headline)

@posts.route("/artikel/<berita>/<string:post_id>", methods=['GET', 'POST'])
def post(berita=None, post_id=None):
    form_comment = CommentForm(prefix='form_comment')
    form_reply = CommentForm(prefix='form_reply')
    post = Post.query.filter_by(slug=post_id, publish=True).first_or_404()
    similar = Post.query.join(Post.tags).filter(Tag.id==post.tags[0].id, Post.id != post.id).order_by(Post.date_posted.desc()).limit(3).all()
    if current_user.is_anonymous:
        post.dibaca += 1
        db.session.commit()
    if form_comment.validate_on_submit():
        comment = Comments(name=form_comment.nama.data, email=form_comment.email.data, 
        website=form_comment.website.data, comment=form_comment.comment.data, publish=True,
        post_id=post.id
        )
        db.session.add(comment)
        db.session.commit()
        flash('Komentar berhasil ditambahkan', 'is-success')
        return redirect(url_for('posts.post', berita=post.category.slug, post_id=post.slug))
    if form_reply.validate_on_submit():
        reply_id = request.form.get('commentId')
        reply = Comments(name=form_reply.nama.data, email=form_reply.email.data, 
        website=form_reply.website.data, comment=form_reply.comment.data, publish=True,
        reply_id=reply_id, post_id=post.id
        )
        db.session.add(reply)
        db.session.commit()
        flash('Balasan komentar berhasil ditambahkan', 'is-success')
        return redirect(url_for('posts.post', berita=post.category.slug, post_id=post.slug))
    return render_template('post/detail.html', post=post, meta=post.title, similar=similar, form_comment=form_comment, form_reply=form_reply)

@posts.route("/category/<string:slug_kategori>")
def kategori(slug_kategori):
    kategori = Kategori.query.all()
    single_kategori = Kategori.query.filter_by(slug=slug_kategori).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(kategori_id=single_kategori.id).order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('post/category.html', kategori=kategori, posts=posts, single_kategori=single_kategori, label='kategori')

@posts.route("/search")
def search():
    search = request.args.get('q', None)
    kata = search.split()
    # agar dapat menggunakan template category
    single_kategori = dict(name=search)
    # end agar dapat menggunakan template category
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter(Post.title.like('%'+kata[0]+'%'), Post.publish==True).order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('post/category.html', posts=posts, label='pencarian', single_kategori=single_kategori)

@posts.route("/topik/<string:slug_tag>")
def topik(slug_tag):
    single_kategori = Tag.query.filter_by(slug=slug_tag).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.join(Post.tags).filter(Tag.slug==slug_tag)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('post/category.html', posts=posts, single_kategori=single_kategori, label='topik')

#pages halaman
@posts.route("/halaman/<string:slug>")
def halaman(slug):
    halaman = Page.query.filter_by(slug=slug).first_or_404()
    return render_template('post/halaman.html', halaman=halaman)

#sitemap xml
@posts.route("/sitemap.xml")
def sitemap_xml():
    artikel = Post.query.order_by(Post.date_posted.desc()).all()
    return render_template('post/sitemap.xml', artikel=artikel, base_url='https://blog.dhanipro.com')

@posts.route("/subscribe", methods=['GET', 'POST'])
def subscribe():
    form = SubscribersForm()
    if form.validate_on_submit():
        sub = Subscribers(email=form.email.data)
        db.session.add(sub)
        db.session.commit()
        flash('Data Anda berhasil disimpan, kami akan mengirim email ke Anda jika ada pembaruan konten', 'is-success is-light')
        return redirect(request.url)
    return redirect(url_for('posts.home'))

portal/templates/post/category.html
{% extends "post/main.html" %}
{% block content %}
            <div class="columns">
                <div class="column">
                    <div class="columns">
                        <div class="column">
                            <p class="title is-4">Artikel berdasarkan {{ label }} <strong class="has-text-info">"{{ single_kategori.name }}"</strong></p>
                        </div>
                    </div>
                    {% for post in posts.items %}
                    <div class="columns">
                        <div class="column is-two-fifths">
                            <figure class="image is-16by9">
                                <a href="{{ url_for('posts.post', berita=post.category.slug, post_id=post.slug) }}">
                                    <img src="{{ url_for('static', filename='upload/img_thumbnail/' + post.image_thumb) }}" alt="{{ post.title }}">
                                </a>
                            </figure>
                        </div>
                        <div class="column">
                            <a class="title is-4 is-marginless" href="{{ url_for('posts.post', berita=post.category.slug, post_id=post.slug) }}">{{ post.title }}</a>
                            <p class="subtitle is-size-7 has-text-grey-light is-marginless">{{ post.date_posted.strftime('%d-%h-%Y') }}</p>
                            <p class="subtitle is-6">{{ post.content|truncate(255)|striptags }}</p>
                        </div>
                    </div>
                    {% endfor %}
                    <section class="section">
                        <div class="columns">
                            <div class="column">
                                {% if posts.has_prev %}
                                <a href="{{ url_for('posts.kategori', slug_kategori=single_kategori.slug, page=posts.prev_num) }}" class="button is-danger is-rounded is-outlined">Prev</a>
                                {% endif %}
                                {% if posts.has_next %}
                                <a href="{{ url_for('posts.kategori', slug_kategori=single_kategori.slug, page=posts.next_num) }}" class="button is-danger is-rounded is-outlined is-pulled-right">Next</a>
                                {% endif %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
{% endblock content %}

portal/templates/post/halaman.html
{% extends "post/main.html" %}
{% block content %}
        <div class="columns">
            <div class="column">
                <nav class="breadcrumb" aria-label="breadcrumbs">
                    <ul>
                        <li><a href="#">Halaman</a></li>
                        <li class="is-active"><a href="#" aria-current="page">{{ halaman.title }}</a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <p class="title is-3">{{ halaman.title }}</p>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <p class="subtitle is-size-7 has-text-grey-light">{{ halaman.date_posted.strftime('%d-%h-%Y') }}</p>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="content">
                    {{ halaman.content | safe }}
                </div>
            </div>
        </div>

{% endblock content %}

portal/templates/post/home.html
{% extends "post/main.html" %}
{% block content %}
        <!-- headline -->
        {% if headline %}
        <div class="columns">
            <div class="column">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-5by3">
                            <a href="{{ url_for('posts.post', berita=headline.category.slug, post_id=headline.slug) }}">
                                <img src="{{ url_for('static', filename='upload/img_thumbnail/' + headline.image_thumb) }}" alt="{{ headline.title }}">
                            </a>
                        </figure>
                    </div>
                    <div class="card-content">
                        <p class="title is-4"><a href="{{ url_for('posts.post', berita=headline.category.slug, post_id=headline.slug) }}">{{ headline.title }}</a></p>
                        <p class="subtitle is-6">{{ headline.content|striptags|truncate(255) }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
            <!-- headline -->
            <div class="columns">
                <div class="column">
                    <div class="columns">
                        <div class="column">
                            <p class="title is-4">Artikel Terbaru</p>
                        </div>
                    </div>
                    {% for post in posts.items %}
                    <div class="columns">
                        <div class="column is-two-fifths">
                            <figure class="image is-16by9">
                                <a href="{{ url_for('posts.post', berita=post.category.slug, post_id=post.slug) }}">
                                    <img src="{{ url_for('static', filename='upload/img_thumbnail/' + post.image_thumb) }}" alt="{{ post.title }}">
                                </a>
                            </figure>
                        </div>
                        <div class="column">
                            <a class="title is-4 is-marginless" href="{{ url_for('posts.post', berita=post.category.slug, post_id=post.slug) }}">{{ post.title }}</a>
                            <p class="subtitle is-size-7 has-text-grey-light is-marginless">{{ post.category.nama_kategori }} {{ post.date_posted.strftime('%d-%h-%Y') }}</p>
                            <p class="subtitle is-6">{{ post.content|striptags|truncate(100) }}</p>
                        </div>
                    </div>
                    {% endfor %}
                    <section class="section">
                        <div class="columns">
                            <div class="column">
                                {% if posts.has_prev %}
                                <a href="{{ url_for('posts.home', page=posts.prev_num) }}" class="button is-dark is-rounded is-outlined">Prev</a>
                                {% endif %}
                                {% if posts.has_next %}
                                <a href="{{ url_for('posts.home', page=posts.next_num) }}" class="button is-dark is-rounded is-outlined is-pulled-right">Next</a>
                                {% endif %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
{% endblock content %}

portal/templates/post/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicons -->
    <!-- <link href="{{ url_for('static', filename='src/icon.png') }}" rel="icon">
    <link href="{{ url_for('static', filename='src/icon.png') }}" rel="apple-touch-icon"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/mystyles.css') }}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <!--adsense-->
    <!-- end adsense -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- End Google Analystyc -->
    {% if meta %}
    <title>{{ post.title }} - {{ blog_name }}</title>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <meta name="description" content="{{ post.content|striptags|truncate(150) }}">
    <meta name="news_keywords" content="{{ post.title }}">
    <!-- facebook -->
    <meta property="og:title" content="{{ post.title }}" />
    <meta property="og:url" content="{{ request.url }}" />
    <meta property="og:image" content="{{ url_for('static', filename='upload/img_thumbnail/' + post.image_thumb) }}" />
    <meta property="og:image:width" content="600" />
    <meta property="og:image:height" content="300" />
    <!-- end facebook -->
    <!-- twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="{{meta}}" />
    <meta name="twitter:description" content="{{ post.content|striptags|truncate(150) }}" />
    <meta name="twitter:image" content="{{ url_for('static', filename='upload/img_thumbnail/' + post.image_thumb, _external=True) }}" />
    <!-- end twitter -->
    {% else %}
        <title>{{ blog_name }}</title>
        <meta name="description" content="Find the latest Programming news from {{ blog_name }}. See related science and technology articles, photos, slideshows and videos.">
    {% endif %}

    {% if title %}
        <title>{{ title }} - {{ blog_name }}</title>
    {% else %}
        <title>{{ blog_name }}</title>
    {% endif %}
  </head>
  <body>
  <!-- <section class="section"> -->
    <progress class="progress is-small is-dark is-radiusless is-marginless" value="100" max="100">15%</progress>
    <div class="container has-background-white box">
        <div class="columns">
            <div class="column is-one-third is-hidden-mobile">
                <a href="/">
                    <h1 class="title is-1 text-logo">{{ blog_name }}</h1>
                </a>
            </div>
            <div class="column has-text-right">
                <img src="{{ url_for('static', filename='upload/728x90ads.png') }}">
            </div>
        </div>

        <!-- Navbar -->
        <div class="columns">
            <div class="column">
                <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
                        <div class="navbar-brand is-hidden-desktop">
                            <a class="navbar-item" href="/">
                                <h1 class="title is-3 has-text-white">{{ blog_name }}</h1>
                            </a>
                            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                                <span aria-hidden="true"></span>
                                <span aria-hidden="true"></span>
                                <span aria-hidden="true"></span>
                            </a>
                        </div>
                    
                <div id="navbarBasicExample" class="navbar-menu">
                    <div class="navbar-start">
                        <a href="/" class="navbar-item">Home</a>
                        {% for k in kategori %}
                        <a href="{{ url_for('posts.kategori', slug_kategori=k.slug) }}" class="navbar-item">{{ k.name }}</a>
                        {% endfor %}
                    </div>

                    <div class="navbar-end">
                        <div class="navbar-item">
                            <form method="GET" action="/search">
                                <div class="field has-addons">
                                        <div class="control">
                                            <input name="q" class="input" type="text" placeholder="Cari...">
                                        </div>
                                        <div class="control">
                                        <button class="button is-success">
                                            Search
                                        </button>
                                        </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    </div>
                </nav>
            </div>
        </div>
        <!-- end-navbar -->
        
        <div class="columns">
            <div class="column is-three-fifths">
                <!-- flash -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="notification {{ category }}">
                {{ message }}
                </div>
                {% endfor %}
                    {% endif %}
                {% endwith %}
                <!-- end flash -->
                {% block content %}{% endblock %}
            </div>
            <!-- sidebar -->
            <div class="column">
                <!-- sidebar ads -->
                <!-- <div class="columns">
                    <div class="column">
                        ads Sidebar
                    </div>
                </div> -->
                <!-- end sidebar ads -->
                <div class="columns">
                    <div class="column">
                        <nav class="panel is-dark">
                            <p class="panel-heading is-radiusless mb-2">
                                Popular Posts
                            </p>
                            {% for p in populer %}
                                <div class="columns pl-1">
                                    <div class="column is-one-third">
                                        <figure class="image is-4by3">
                                            <img src="{{ url_for('static', filename='upload/img_thumbnail/' + p.image_thumb) }}" alt="{{ p.title }}" style="object-fit: cover;">
                                        </figure>
                                    </div>
                                    <div class="column">
                                        <p><a class="title is-6" href="{{ url_for('posts.post', berita=p.category.slug, post_id=p.slug) }}">{{ p.title }}</a></p>
                                        <p class="subtitle is-size-7 has-text-grey-light">{{ p.date_posted.strftime('%d-%h-%Y') }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </nav>
                    </div>
                </div>
                <section class="section-custom"></section>
                <div class="columns">
                    <div class="column">
                        <nav class="panel is-dark">
                            <p class="panel-heading is-radiusless">
                                Tags
                            </p>
                            <div class="columns px-1 py-1">
                                <div class="column">
                                    <div class="tags">
                                        {% for tag in topik %}
                                        <span class="tag is-black">
                                            <a class="has-text-white" href="{{ url_for('posts.topik', slug_tag=tag.slug) }}">{{ tag.name }}</a>
                                        </span>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
                <!-- block subscribe -->
                    {% include "post/subscribe.html" %}
                <!-- end block subscribe -->
            </div>
        </div>
    </div>
    <!-- footer -->
    <footer class="footer has-background-dark is-paddingless">
        <div class="has-text-centered py-5">
            <nav class="breadcrumb has-bullet-separator is-centered" aria-label="breadcrumbs">
                <ul>
                    {% for page in pages %}
                    <li><a href="{{ url_for('posts.halaman', slug=page.slug) }}" class="has-text-white">{{ page.title }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
            <p class="has-text-white">{{ blog_name }}|Copyright &copy; {{ now }}</p>
        </div>
    </footer>
    <!-- end-footer -->
  <!-- </section> -->
  <script>
      const navbarBurgers = document.getElementsByClassName('navbar-burger')[0];
      const navbarMenu = document.getElementsByClassName('navbar-menu')[0];
      const burgerClick = navbarBurgers.addEventListener('click', tampilMenu);

      function tampilMenu(){
        navbarBurgers.classList.toggle('is-active');
        navbarMenu.classList.toggle('is-active');
      }

      function outsideClick(e){
            if(e.target){ 
                element.classList.remove("is-active");            
            }
        
        }
  </script>
  </body>
</html>

portal/templates/post/post.html
{% extends "main.html" %}
{% block content %}
    <div class="row">

        <div class="col-md-8">
            <div class="blog-post">
                <h2 class="blog-post-title">{{ post.title }}</h2>
                <p class="blog-post-meta">{{ post.date_posted.strftime('%d-%m-%Y') }} Oleh <a href="#">{{ post.author.username }}</a></p>

                {{ post.content | safe }}
            </div><!-- /.blog-post -->
            <div class="mb-4">
                Topik: 
            {% for t in post.tags %}
                <a href="{{ url_for('posts.topik', name=t.name) }}" class="badge badge-success">{{ t.name }}</a>
            {% endfor %}
            </div>
        </div>
        <div class="col-md-4">
            <!-- <div class="card p-4">
                iklan google
            </div> -->

            <div class="p-3 mb-3 bg-light rounded">
                <h4 class="font-italic">Topik Terpopuler</h4>
                <p class="mb-0">
                    {% for t in topik %}
                    <a href="{{ url_for('posts.topik', name=t.name) }}" class="badge badge-success">{{ t.name }}</a>
                    {% endfor %}
                </p>
            </div>

            <div class="p-4 bg-light rounded">
                <h4 class="mb-3 font-italic">Artikel Populer</h4>
                {% for p in populer %}
                <div class="media mb-3">
                    <img class="mr-3" width="64" height="auto" src="{{ url_for('static', filename='upload/img_thumbnail/' + p.image_thumb) }}" alt="{{ p.title }}">
                    <div class="media-body">
                    <h5 class="mt-1"><a href="{{ url_for('posts.post',berita=p.category.nama_kategori, post_id=p.slug) }}">{{ p.title|truncate(30, false) }}</a></h5>
                    {{ p.content|truncate(100, false)|striptags }}
                    </div>
                </div>
                {% endfor %}
            </div>
            
            <div class="p-4">
                <h4 class="font-italic">Sosial</h4>
                <ol class="list-unstyled">
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>

        </div>

    </div>

{% endblock content %}

portal/templates/post/subscribe.html
{% block subscribe %}
<div class="columns">
  <div class="column">
    <div class="box">
      <p class="title is-5 has-text-centered">Ikuti Melalui Email</p>
      <p class="subtitle is-6 has-text-centered">Dapatkan info terbaru, dikirim ke email Anda</p>
      <form method="POST" action="{{ url_for('posts.subscribe') }}">
        {{ form.hidden_tag() }}
        <div class="field">
          <div class="control">
              {% if form.email.errors %}
                  {{ form.email(class="input has-text-centered") }}
                  {% for error in form.email.errors %}
                    <p class="help is-danger">{{ error }}</p>
                  {% endfor %}
              {% else %}
                  {{ form.email(class="input has-text-centered") }}
              {% endif %}
          </div>
        </div>
        <div class="field">
          <div class="control">
            {{ form.submit(class="button is-info is-fullwidth") }}
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock subscribe %}